#coding:utf-8
import HTMLTestRunner
import unittest
#from test_report.config import *
from test_case.TestCase import *
#from test_case.test_case import  *
suite = unittest.TestSuite()
tests = [TestCase("test_login")]
#tests = [test_login_1]
suite.addTests(tests)
with open('HTMLReport.html', 'w') as f:
    runner = HTMLTestRunner.HTMLTestRunner(stream=f,
                                           title='test_report',
                                           description='generated by HTMLTestRunner.',
                                           verbosity=2
                                           )
    runner.run(suite)
